### ISSUE TITLE
todolist 개인 과제를 하며 고민했던 부분입니다.

### ISSUE THREAD

**Issue by v-va** [v-va/assignment#1]
완료와 취소 버튼을 처음부터 잘못 설계했다. 막연히 버튼이 2개이기 때문에 각각 함수를 만들어 줄 요량이었다. 다른 문제로 매니저님께 질문을 하러 갔다가 둘은 결국 하나의 일을 하기 때문에 하나의 함수를 사용하는게 맞다는 이야기를 해주셔서 그렇게 변경해야겠다고 생각하였다. 리액트는 재사용성이 중요하므로!!

이 과정에서 궁금한 부분이 생겼다.

## 1. 함수가 실행될 때마다 데이터의 값을 set 해주는 것만으로는 리랜더링 되기에 부족한걸까?

```js
// todolist 객체
const [todolist, setTodolist] = useState([
  { id: 5, done: true, title: "TIL 작성", content: "오늘 자 TIL 작성하기" },
]);

// 완료 버튼 클릭
const clickIsDoneHandler = (id) => {
    const doneTodo = todolist.filter((todo) => {
        return todo.id === id
    })[0].done = true

    setDone(doneTodo)
}
```

처음에 짰던 코드인데, 여기서 궁금한 점은
filter로 뽑긴 했지만 done 값을 변경해주었고,
setDone 이라는 행동을 통해 리랜더링 되도록 해 주었는데

**동작하는 것을 보면 첫 클릭 시에는 잘 동작하지만,
그 이후부터는 콘솔에서만 변경된 값을 확인할 수 있고, 
리랜더링 되지 않는다는 점이다.** 

**내가 가진 개념 상 분명 set이라는 동작이 있고, 버튼을 클릭 할 때 마다 해당 함수가 실행되니까 변경이 되야할 것 같은데(...?)**
아니면 만약 객체 값 자체에 접근해서 바꾸는게 안되고, 객체 전체를 리랜더링 해줘야 하는 거라면 아예 동작하지 않아야 할 것 같은데 말이다.

잘 모르겠지만 뭔가 중요한 개념을 놓치고 있는 기분이 든다 T-T

## 2. todo를 표시하는 박스를 그려주는 Todobox 컴포넌트를 분리하며 느낀점
App.js 에서 filter를 사용하여 todolist 객체를 done 상태 값을 통해 구분하고, map으로 출력하면서 map의 리턴 값에 Todobox라는 컴포넌트를 사용하였다.

이 컴포넌트에도 삼항연산자를 이용해 done의 상태가 true일 때와 false일 때로 나눠서 리턴하도록 만들었다.

궁금한 부분은 **todolist를 이미 done 상태를 이용하여 데이터를 걸러서 가지고 오는데, 왜 Todobox에서도 삼항연산자를 이용하여 조건을 나누어 출력해줘야 하는걸까?**

내 추측으로는, todolist를 걸러서 가지고 오는건 데이터의 입장이고, 
Todobox에서 걸러서 출력하는건 그려지는 입장이라 나눠서 해줘야 하는 건가?
싶은 생각이 든다. 이 부분이 좀 햇갈린다.

## 3. todo를 추가하기 위한 컴포넌트를 분리하며 느낀점
input 태그가 포함된 부분을 컴포넌트화 하여 파일 분리를 하였다. 그랬더니 input 창에 [object Object] 라고 떠있고, 값을 수정할 수가 없었다.

구글링을 통해 value를 defaultValue로 수정해주면 된다는 것을 알게되어 적용해보니 값을 수정할 수는 있는데, **초기 값은 그대로 [object Object]로 떠있다. 그리고 버튼을 눌러도 아무 동작을 하지 않는다.**

value 값을 상위 객체에서 props로 받아서 그대로 출력하는데 왜 이렇게 되는 걸까? 잘 모르겠다 T-T

긴 글 읽어주셔서 감사합니다.
나중에 제가 다시 보기 위해 자세히 적었습니다 😅

**Comment by v-va** [comment]
1번의 답은 찾았습니다!
리액트 상태에서 객체를 수정해야 할 때에는, **직접 수정하면 안됩니다.**
그 대신에, **새로운 객체를 만들어서 새로운 객체에 변화를 주고,** 이를 상태로 사용해주어야 합니다.
이러한 작업을, **"불변성을 지킨다"** 라고 부릅니다. 불변성을 지켜주어야만 리액트 컴포넌트에서 상태가 업데이트가 됐음을 감지 할 수 있고 이에 따라 필요한 리렌더링이 진행됩니다.
[참조링크](https://react.vlpt.us/basic/09-multiple-inputs.html)

**Comment by epppo** [comment]
2번에 대한 답입니다~ :)  
done 과 work 는 한번만 분리하셔도 됩니다.  코드를 보니 처음에 app.js 에서  필터할 때도 한번 분리하셨고 , Todobox.jsx 박스 내에서도 한번 더 분리하셔서 TodoBox에서는 불필요한 작업이 한번 더 진행되었어요 .
TodoBox는 프롭스로 전달받은 데이터를 기반으로 하나의 작은 박스를 그리는데에만 데이터와 랜더링에 초점을 주시면되고 
실재로 done과 work 는  app.js  내에서만 분리를 해주시면 됩니다 :)

**Comment by epppo** [comment]
3번은 분리한 컴포넌트 구조와 코드 확인이 어려워서 제가 정확한 답변을 드리기 어렵겠네요,  오늘 순회시간에 분리한 코드까지 확인해보고 답변 드릴게요 : )

**Comment by v-va** [comment]
답변 감사합니다 🥰💕
